services:
    app.product.voter:
        class: TradeBundle\Security\ProductVoter
        tags: 
            - { name: security.voter }
#    trade.example:
#        class: TradeBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
