app_user:
    resource: "@AppBundle/Controller/UserController.php"
    type:     annotation

trade:
    resource: "@TradeBundle/Controller/"
    type:     annotation
    prefix:   /

app:
    resource: '@AppBundle/Controller/'
    type: annotation
