<?php

namespace TradeBundle\Repository;

/**
 * MoneyTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoneyTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
